version: '3'

services:
  janus-gateway:
    image: quay.io/tkaefer/docker-janus
    container_name: janus-gateway
    volumes:
      - ./volumes/janus/etc/janus/:/opt/janus/etc/janus/
      - ./volumes/janus/janus.log:/var/log/janus.log
    ports:
      - 7088:7088
      - 8188:8188
      - 8088:8088
  nginx:
    image: nginx:alpine
    volumes:
      - ./volumes/nginx/conf/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./volumes/nginx/www/html:/usr/share/nginx/html:ro
#      - ./volumes/nginx/certs/server.crt:/usr/local/nginx/server.crt
#      - ./volumes/nginx/certs/server.key:/usr/local/nginx/server.key
    ports:
      - 80:80
